### PR TITLE
Serialization firstpass

### PR DESCRIPTION
**Pull request by schuyler1d**
I made a PR to CowboyTim/python-storable but since you maintain the PyPI module `storable`, I'm sending a PR your way, as well, to also pick up updates from CowboyTim and also my recent serialization work on top of that.

### CODE REVIEW

**Comment by mike-hart** [comment]
This is probably going to take me some time to look through, so apologies if it takes a while.

I mostly started on this project because I wanted to be able to read some Perl storables from a database at my place of employment and didn't want to have to go through Perl to get them, I haven't needed to do that in quite a while though.

I'll be reading the patches individually (and I think there are around 80 of them?) since otherwise I'd be reading one massive merge without context. I _will_ get back to you though.

**Comment by schuyler1d** [comment]
Wow, that was *very* fast. I have the same use case: a project that needs to read (and now write) to perl, but hoping I don't ever again ;-)

Thanks for your work and community maintenance!

**Comment by mike-hart** [comment]
You're welcome.

I've possibly got a few cleanups coming (minor things, spelling errors, punctuation, some uses of a list-comp when a genexp would work fine, renaming of variables in the perl to avoid perlcritic complaints, etc.).

**Comment by mike-hart** [comment]
If I could get your eyes on #2 I'd appreciate it.

**Pull request merged**
